server:
  port: 9000
spring:
  application:
    name: homebox-boot-dubbo-order
dubbo:
  application:
    name: homebox-boot-dubbo-order
    registry: zookeeper://localhost:2181
  scan:
    base-packages: top.hapleow.homeboxbootdubbouser.service
  protocol:
    port: 20881