server:
  port: 9000
spring:
  application:
    name: homebox-boot-dubbo-order
dubbo:
  application:
    name: homebox-boot-dubbo-order
    registries: zookeeper://localhost:2180,zookeeper://localhost:2181,zookeeper://localhost:2182
  scan:
    base-packages: top.hapleow.homeboxbootdubbouser.service
  protocol:
    port: 20881