spring:
  application:
    name: order-service-app
  datasource:
    url: jdbc:mysql://localhost:3306/homebox?useUtf8=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: top.hapleow.orderserviceapp.service
  protocol:
    port: 9001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: h_
nacos:
  config:
    server-addr: 127.0.0.1:8848
