spring:
  application:
    name: user-service-app

dubbo:
  application:
    registries: zookeeper://localhost:2180,zookeeper://localhost:2181,zookeeper://localhost:2182
  scan:
    base-packages: top.hapleow.userserviceapp.service

